spring:
  profiles:
    active: dev

sharding.jdbc:
  data-sources:
    ds_master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/my_springboot?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false&useSSL=false
      username: root
      password: root
    ds_slave_0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/my_springboot?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false&useSSL=false
      username: root
      password: root
      
  master-slave-rule:
    name: ds_ms
    master-data-source-name: ds_master
    slave-data-source-names: ds_slave_0
    load-balance-algorithm-type: round_robin
    
redisson:
  #redis链接地址
  address: redis://
  password: password

  #master-name: mymaster
  #password: xxxx
  #sentinel-addresses: redis.peanut.ai:6379,redis.peanut.ai:16379,redis.peanut.ai:26379
  #masterName:
  #当前处理核数量 * 2
  thread: 4
  #指定编解码
  #codec: org.redisson.codec.JsonJacksonCodec
  #最小空闲连接数,默认值:10,最小保持连接数（长连接）
  connectionMinimumIdleSize: 12
  #连接空闲超时，单位：毫秒 默认10000;当前连接池里的连接数量超过了最小空闲连接数，
  #而连接空闲时间超过了该数值，这些连接将会自动被关闭，并从连接池里去掉
  idleConnectionTimeout: 10000
  #ping节点超时,单位：毫秒,默认1000
  pingTimeout: 1000
  #连接等待超时,单位：毫秒,默认10000
  connectTimeout: 10000
  #命令等待超时,单位：毫秒,默认3000；等待节点回复命令的时间。该时间从命令发送成功时开始计时
  timeout: 3000
  #命令失败重试次数，默认值:3
  retryAttempts: 2
  #命令重试发送时间间隔，单位：毫秒,默认值:1500
  retryInterval: 1500
  #重新连接时间间隔，单位：毫秒,默认值：3000;连接断开时，等待与其重新建立连接的时间间隔
  reconnectionTimeout: 3000
  #执行失败最大次数, 默认值：3；失败后直到 reconnectionTimeout超时以后再次尝试。
  failedAttempts: 3
  #单个连接最大订阅数量，默认值：5
  subscriptionsPerConnection: 5
  #客户端名称
  #clientName:
  #发布和订阅连接的最小空闲连接数，默认值：1；Redisson内部经常通过发布和订阅来实现许多功能。
  #长期保持一定数量的发布订阅连接是必须的
  subscriptionConnectionMinimumIdleSize: 1
  #发布和订阅连接池大小，默认值：50
  subscriptionConnectionPoolSize: 50
  #连接池最大容量。默认值：64；连接池的连接数量自动弹性伸缩
  connectionPoolSize: 64
  #数据库编号，默认值：0
  database: 0
  #是否启用DNS监测，默认值：false
  dnsMonitoring: false
  #DNS监测时间间隔，单位：毫秒，默认值：5000
  dnsMonitoringInterval: 5000
  slaveConnectionPoolSize: 10
  masterConnectionPoolSize: 10
  #sentinelAddresses:
